{ 
"1-3:0.2.8": ["Version information for P1 output", "dsmr_version", "^.*\((.*)\)"],
"0-0:1.0.0": ["Date-time stamp of the P1 message", "timestamp", "^.*\((.*)\)"],
"0-0:96.1.1": ["Equipment identifier", "serial", "^.*\((.*)\)"],
"0-0:96.7.9": ["Number of long power failures in any phase", "long_power_failures", "^.*\((.*)\)"],
"1-0:32.36.0": ["Voltage swells in phase L1", "voltage_swells_l1", "^.*\((.*)\)"],
"1-0:52.36.0": ["Voltage swells in phase L2", "voltage_swells_l2", "^.*\((.*)\)"],
"1-0:72.36.0": ["Voltage swells in phase L3", "voltage_swells_l3", "^.*\((.*)\)"],
"1-0:21.7.0": ["Instantaneous active power L1 (+P) in W resolution", "current_watts_consumed_l1_kw", "^.*\((.*)\*kW\)"],
"1-0:41.7.0": ["Instantaneous active power L2 (+P) in W resolution", "current_watts_consumed_l2_kw", "^.*\((.*)\*kW\)"],
"1-0:61.7.0": ["Instantaneous active power L3 (+P) in W resolution", "current_watts_consumed_l3_kw", "^.*\((.*)\*kW\)"],
"1-0:32.32.0": ["Number of voltage sags in phase L1", "voltage_sags_l1", "^.*\((.*)\)"],
"1-0:52.32.0": ["Number of voltage sags in phase L2", "voltage_sags_l2", "^.*\((.*)\)"],
"1-0:72.32.0": ["Number of voltage sags in phase L3", "voltage_sags_l3", "^.*\((.*)\)"],
"0-1:24.2.1": ["Last 5-minute Meter reading and capture time (e.g. slave E meter)", "consumed_gas", "^.*\((.*)\*m3\)"],
"1-0:22.7.0": ["Instantaneous active power L1 (-P) in W resolution", "current_watts_generated_l1_kw", "^.*\((.*)\*kW\)"],
"1-0:42.7.0": ["Instantaneous active power L2 (-P) in W resolution", "current_watts_generated_l2_kw", "^.*\((.*)\*kW\)"],
"1-0:62.7.0": ["Instantaneous active power L2 (-P) in W resolution", "current_watts_generated_l3_kw", "^.*\((.*)\*kW\)"],
"0-0:96.7.21": ["Number of power failures in any phase", "any_power_failures", "^.*\((.*)\)"],
"0-1:24.1.0": ["Device-Type", "device_type", "^.*\((.*)\)"],
"0-1:96.1.0": ["Equipment Identifier", "serial_gas", "^.*\((.*)\)"],
"0-0:96.14.0": ["Tariff indicator elec- tricity. The tariff in- dicator can also be used to switch tariff dependent loads e.g boilers. This is the responsibility of the P1 user", "tariff_indicator", "^.*\((.*)\)"],
"1-0:99.97.0": ["Power Failure Event Log (long power failures)", "power_failure_event_log", "^.*\((.*)\)"],
"1-0:32.7.0": ["Instantaneous voltage L1 in V resolution", "voltage_l1_v", "^.*\((.*)\*V\)"],
"1-0:52.7.0": ["Instantaneous voltage L2 in V resolution", "voltage_l2_v", "^.*\((.*)\*V\)"],
"1-0:72.7.0": ["Instantaneous voltage L3 in V resolution", "voltage_l3_v", "^.*\((.*)\*V\)"],
"1-0:31.7.0": ["Instantaneous current L1 in A resolution.", "power_consumed_l1_a", "^.*\((.*)\*A\)"],
"1-0:51.7.0": ["Instantaneous current L2 in A resolution.", "power_consumed_l2_a", "^.*\((.*)\*A\)"],
"1-0:71.7.0": ["Instantaneous current L3 in A resolution.", "power_consumed_l3_a", "^.*\((.*)\*A\)"],
"0-0:96.13.0": ["Text message max 1024 characters.", "text_message", "^.*\((.*)\)"],
"0-0:96.13.1": ["Text message max 1024 characters.", "text_message", "^.*\((.*)\)"],
"1-0:1.8.1": ["Meter Reading electricity delivered to client (Tariff 1) in 0,001 kWh", "power_consumed_tariff_1_kwh", "^.*\((.*)\*kWh\)"],
"1-0:1.8.2": ["Meter Reading electricity delivered to client (Tariff 2) in 0,001 kWh", "power_consumed_tariff_2_kwh", "^.*\((.*)\*kWh\)"],
"1-0:2.8.1": ["Meter Reading electricity delivered by client (Tariff 1) in 0,001 kWh", "power_produced_tariff_1_kwh", "^.*\((.*)\*kWh\)"],
"1-0:2.8.2": ["Meter Reading electricity delivered by client (Tariff 2) in 0,001 kWh", "power_produced_tariff_2_kwh", "^.*\((.*)\*kWh\)"],
"1-0:1.7.0": ["Actual electricity power delivered (+P) in 1 Watt resolution", "power_consumed_kw", "^.*\((.*)\*kW\)"],
"1-0:2.7.0": ["Actual electricity power received (-P) in 1 Watt resolution", "power_produced_kw", "^.*\((.*)\*kW\)"],
}
